### ISSUE TITLE
Immer support

### ISSUE THREAD

**Issue by drumnation** [generalui/hooks-for-redux#2]
I'm trying to refactor from redux toolkit, but prefer the immer syntax. Trying to figure out a way to use this same pattern with immer syntax reducers.

I've tried swapping the combineReducers function in `hooks-for-redux` with  `redux-immer` https://www.npmjs.com/package/redux-immer and adding immer, but that wasn't working. Kept getting an error that it couldn't find immer's produce method.

**Comment by shanebdavis** [comment]
Could you sketch what you think the client-developer's experience might look like?

**Comment by ArturBaybulatov** [comment]
> Could you sketch what you think the client-developer's experience might look like?

Based on the example at https://github.com/shanebdavis/rtk-github-issues-example-h4r-conversion/blob/master/src/redux/issuesDisplay.ts, the experience would be similar to what Redux Toolkit did to plain Redux.

So, currently code with H4R looks like this (no mutations allowed in reducers):

```ts
export const [
  useIssuesDisplay,
  {showIssueDetails, showIssuesList},
  issuesDisplayStore,
] = useRedux('issuesDisplay', initialState, {
  showIssueDetails: (state, issue: Issue) =>
    Object.assign({}, state, {displayType: 'comments', issue}),

  showIssuesList: state =>
    Object.assign({}, state, {displayType: 'issues', issue: null}),
});
```

After, with Immer integration it's going to look like this (mutations are allowed):

```ts
export const [
  useIssuesDisplay,
  {showIssueDetails, showIssuesList},
  issuesDisplayStore,
] = useRedux('issuesDisplay', initialState, {
  showIssueDetails: (state, issue: Issue) => {
    state.displayType = 'comments';
    state.issue = issue;
  },

  showIssuesList: state => {
    state.displayType = 'issues';
    state.issue = null;
  },
});
```

**Comment by drumnation** [comment]
Without a higher level integration I've been using immer like this.

```
createReduxModule('editorProjectDocuments', initialState, {
  addAsset: produce(
    (state: ProjectDocumentsState, item: IAsset | IUploadAsset) => {
      const assetIds = Array.from(new Set([item.key, ...state.assetIds]));
      state.assetIds = assetIds;
      state.assets[item.key] = { ...item, id: item.key };
      state.projectDocuments[state.projectId].assets = assetIds;
      log.state('[redux] add asset', { asset: item });
    },
  ),
```

So the higher level integration would remove the need to wrap everything in a produce function or to import that function in every reducer.  It would look like what @[**ArturBaybulatov**](https://github.com/ArturBaybulatov) posted above.

**Comment by shanebdavis** [comment]
Thanks for the idea, but there are no immediate plans to implement this.
